### PR TITLE
Fix missing library packaging

### LINKED ISSUE #767: [Bug]: No module named "packaging" when importing hdmf.common
### What happened?

Error when importing hdmf.common.

Related to https://github.com/hdmf-dev/hdmf/pull/762/files

Apparently `import hdmf` is OK but `import hdmf.common` is not, so the CI succeeded.

### Steps to Reproduce

```shell
conda create --name test python=3.9 --yes
pip install hdmf
python -c "import hdmf.common"
```

### Traceback

```shell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/miniconda3/envs/test/lib/python3.9/site-packages/hdmf/common/__init__.py", line 200, in <module>
    from . import io as __io  # noqa: F401,E402
  File "/opt/miniconda3/envs/test/lib/python3.9/site-packages/hdmf/common/io/__init__.py", line 4, in <module>
    from . import alignedtable  # noqa: F401
  File "/opt/miniconda3/envs/test/lib/python3.9/site-packages/hdmf/common/io/alignedtable.py", line 2, in <module>
    from ..alignedtable import AlignedDynamicTable
  File "/opt/miniconda3/envs/test/lib/python3.9/site-packages/hdmf/common/alignedtable.py", line 8, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
```

### Operating System

macOS

### Python Executable

Conda

### Python Version

3.9

### Package Versions

# packages in environment at /opt/miniconda3/envs/test:
#
# Name                    Version                   Build  Channel
ca-certificates           2022.07.19           hca03da5_0  
certifi                   2022.6.15        py39hca03da5_0  
h5py                      3.7.0                    pypi_0    pypi
hdmf                      3.4.3                    pypi_0    pypi
libcxx                    14.0.6               h848a8c0_0  
libffi                    3.4.2                hc377ac9_4  
ncurses                   6.3                  h1a28f6b_3  
numpy                     1.23.3                   pypi_0    pypi
openssl                   1.1.1q               h1a28f6b_0  
pandas                    1.4.4                    pypi_0    pypi
pip                       22.1.2           py39hca03da5_0  
python                    3.9.13               hbdb9e5c_1  
pytz                      2022.2.1                 pypi_0    pypi
readline                  8.1.2                h1a28f6b_1  
scipy                     1.9.1                    pypi_0    pypi
setuptools                63.4.1           py39hca03da5_0  
sqlite                    3.39.2               h1058600_0  
tk                        8.6.12               hb8d0fd4_0  
tzdata                    2022c                h04d1e81_0  
wheel                     0.37.1             pyhd3eb1b0_0  
xz                        5.2.5                h1a28f6b_1  
zlib                      1.2.12               h5a0b063_3

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/hdmf-dev/hdmf/blob/dev/.github/CODE_OF_CONDUCT.md)
- [X] Have you checked the [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this bug was not already [reported](https://github.com/hdmf-dev/hdmf/issues)?

### PR DESCRIPTION
**Pull request by rly**
## Motivation

Fix #767 

## Checklist

- [x] Did you update CHANGELOG.md with your changes?
- [x] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?
- [x] Have you ensured the PR clearly describes the problem and the solution?
- [x] Is your contribution compliant with our coding style? This can be checked running `flake8` from the source directory.
- [x] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/hdmf-dev/hdmf/pulls) for the same change?
- [x] Have you included the relevant issue number using "Fix #XXX" notation where XXX is the issue number? By including "Fix #XXX" you allow GitHub to close issue #XXX when the PR is merged.

### CODE REVIEW

**Comment by oruebel** [comment]
My mistake. Based on what I was reading online, I thought ``packaging`` was being installed with ``setuptools``, which is why I had not added it as an explicit dependency. 

Since ``packaging`` is only used in one place to compare pandas versions, instead of adding it as a dependency it may be worth to replace the code the compares pandas version with something that doesn't add a new requirement:

``if version.parse(pd.__version__) >= version.parse("1.5.0"):``

E.g., the following should work for Pandas versions:

``if tuple([int(i) for i in pd.__version__.split(".") if i.isnumeric()]) >= (1, 5, 0)``

**Review by oruebel — APPROVED** [review]

**Comment by rly** [comment]
@oruebel, let's go with the pandas specific approach that you outlined above, so that we avoid adding another dependency.

**Comment by rly** [comment]
@oruebel could you start a new PR with that change? and add the change from this PR on `tox.ini`?

**Comment by oruebel** [comment]
> could you start a new PR with that change? and add the change from this PR on `tox.ini`?

Sounds good, will do.

**Comment by oruebel** [comment]
Suggested fix is implemented in https://github.com/hdmf-dev/hdmf/pull/770

**Pull request closed without merging**
