### PR TITLE
include count in html

### PR DESCRIPTION
**Pull request by bendichter**
image

### CODE REVIEW

**Comment by oruebel** [comment]
Looks good to me. Can you please update the tests.

**Comment by rly** [comment]
I like this one the best too.

**Comment by bendichter** [comment]
<html><div class=\'container-wrap\'><div class=\'container-header\'><div class=\'xr-obj-type\'><h3>FooSingle</h3></div></div><details><summary style="display: list-item; margin-left: 0px;" class="container-fields field-key" title=".fields[\'containers\']"><b>containers (2)</b></summary><details><summary style="display: list-item; margin-left: 20px;" class="container-fields field-key" title=".fields[\'containers\'][\'obj1\']"><b>obj1</b></summary></details><details><summary style="display: list-item; margin-left: 20px;" class="container-fields field-key" title=".fields[\'containers\'][\'obj2\']"><b>obj2</b></summary></details></details></div></html>

**Comment by bendichter** [comment]
@rly @oruebel ok, this is ready to go

**Review by oruebel — APPROVED** [review]

**Pull request merged**
