### PR TITLE
Fix checking of docval shape on types without len

### LINKED ISSUE #103: Docval shape cannot be checked on types without len
When shape is defined for a docval argument and type can be an object that does not have a `__len__`, e.g. `ElectricalSeries.data`
```python
class ElectricalSeries(TimeSeries):
    @docval(...
            {'name': 'data', 'type': ('array_data', 'data', TimeSeries),
             'shape': ((None, ), (None, None), (None, None, None)),
             'doc': 'The data this TimeSeries dataset stores. Can also store binary data e.g. image frames'},
             ...)
```
then doing a direct link between data of one ElectricalSeries and another:
```python
ts1 = ElectricalSeries('test_ts1', [0, 1, 2, 3, 4, 5], region, timestamps=[0.0, 0.1, 0.2, 0.3, 0.4, 0.5])
ts2 = ElectricalSeries('test_ts2', ts1, region, timestamps=[0.0, 0.1, 0.2, 0.3, 0.4, 0.5])
```
results in the error: 
```
Traceback (most recent call last):
  File "C:\Users\Ryan\Documents\NWB\temp\pynwb\tests\unit\test_ecephys.py", line 42, in test_timestamps_link
    ts2 = ElectricalSeries('test_ts2', ts1, region, timestamps=[0.0, 0.1, 0.2, 0.3, 0.4, 0.5])
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\utils.py", line 379, in func_call
    allow_extra=allow_extra)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\utils.py", line 176, in __parse_args
    if not __shape_okay_multi(argval, arg['shape']):
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\utils.py", line 71, in __shape_okay_multi
    return any(__shape_okay(value, a) for a in argshape)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\utils.py", line 71, in <genexpr>
    return any(__shape_okay(value, a) for a in argshape)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\utils.py", line 78, in __shape_okay
    if not len(valshape) == len(argshape):
TypeError: object of type 'NoneType' has no len()
```

### PR DESCRIPTION
**Pull request by rly**
Fixes #103

### CODE REVIEW

**Comment by bendichter** [comment]
This will allow data in that does not match the spec. Another option would be to do something like:

```python
if isinstance(argval, hdmf.Container):
    argval = getattr(argval, argname)
```

before the shape checks

**Comment by bendichter** [comment]
Actually I guess we can assume that if it was written once it was write the first time so it will also be right this time.

**Comment by rly** [comment]
Good idea. 

But I don't think we can assume the passed-in objects have been written to file. You can still create in-memory objects and pass them around. The only places I have seen where `shape` is specified for a docval argument with a Container `type` is for data and timestamps, which have this unpacking/chaining ability. I updated the code to reflect that. Note that we cannot import Container because it would be a circular import.

**Comment by bendichter** [comment]
Yeah they haven't been written to file but they have gone through docval at least once to be written to memory. Ultimately I am fine with either way. This looks good to me

**Review by bendichter — APPROVED** [review]

**Pull request merged**
