### PR TITLE
Fix check quantity for non-data-type datasets

### PR DESCRIPTION
**Pull request by rly**
## Motivation

When datasets without a `data_type_def` or `data_type_inc` (and therefore must have a name) are encountered, the `ObjectMapper` raises an error when checking quantity. This PR should fix that error.

This is blocking the release of HDMF 3.0.

## Checklist

- [x] Did you update CHANGELOG.md with your changes?
- [x] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?
- [x] Have you ensured the PR clearly describes the problem and the solution?
- [x] Is your contribution compliant with our coding style? This can be checked running `flake8` from the source directory.
- [x] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/hdmf-dev/hdmf/pulls) for the same change?
- [x] Have you included the relevant issue number using "Fix #XXX" notation where XXX is the issue number? By including "Fix #XXX" you allow GitHub to close issue #XXX when the PR is merged.

### CODE REVIEW

**Comment by rly** [comment]
TODO: Add a test for this.

**Comment by rly** [comment]
I added tests. This is ready for review.

**Review by oruebel — APPROVED** [review]
It would be good to also raise a warning in the spec object when a users tries to  create an untyped object with a quantity other than `?`, `zero_or_one`, or `1`. Ignoring the quantity in the object mapper is probably fine here, because you should not be able to create an untyped object more than once, but in the spec we'd need to check for all three possible settings. Updating the spec object to warn on bad values does not need to be part of this PR, but we should probably make an issue to improve error checking in the Spec objects in general, and this is just one case that needs to be checked for.

**Comment by rly** [comment]
Thanks. I agree, and I think that should be in a separate PR.

**Review by ajtritt — APPROVED** [review]

**Pull request merged**
