### PR TITLE
Fixes for getting validation against cached namespace information working

### PR DESCRIPTION
**Pull request by t-b**
These changes here are required for https://github.com/NeurodataWithoutBorders/pynwb/pull/944.
Before merging we need to find a solution for 428ec63, reverting was the only way for me to get validation working.

### CODE REVIEW

**Comment by bendichter** [comment]
why did we need to revert a16cc63e9065b92673d175fd9e55a86c6eb46d54? What was the issue with the validator that requires you to read all vectors of strings on `read`?

**Comment by t-b** [comment]
@bendichter Because of #68, I don't want to revert a16cc63, I just needed a hack to get validation working.

**Comment by bendichter** [comment]
I see.. so maybe we could allow time vectors to be objects?

**Comment by t-b** [comment]
@bendichter Or just fix the parts in pynwb which reads them. But I have not found these.

**Comment by bendichter** [comment]
The issue is you wouldn't be able to know it's a date until you read the string.

**Comment by oruebel** [comment]
> The issue is you wouldn't be able to know it's a date until you read the string

Do we have the schema accessible at that time? If so, the isodatetime type should be specified there. 

>  I just needed a hack to get validation working.

Could the validator not simply read the string when it validates date times?

**Review by ajtritt — DISMISSED** [review]

**Comment by t-b** [comment]
@ajtritt Thanks for the review. Just to avoid a mess I've removed the reverting commit. Once #74 is merged this PR is from POV good to go.

**Review by rly — APPROVED** [review]

**Comment by rly** [comment]
@t-b is this good to merge? if so, please merge. thanks

**Comment by t-b** [comment]
@rly Ready to merge. But I'm not allowed to merge!

**Comment by rly** [comment]
Oops, my bad!

**Pull request merged**
