### PR TITLE
Gallery Bug

### PR DESCRIPTION
**Pull request by mavaylon1**
## Motivation

What was the reasoning behind this change? Please explain the changes briefly.

## How to test the behavior?
```
Show how to reproduce the new behavior (can be a bug fix or a new feature)
```

## Checklist

- [ ] Did you update CHANGELOG.md with your changes?
- [ ] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?
- [ ] Have you ensured the PR clearly describes the problem and the solution?
- [ ] Is your contribution compliant with our coding style? This can be checked running `flake8` from the source directory.
- [ ] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/hdmf-dev/hdmf/pulls) for the same change?
- [ ] Have you included the relevant issue number using "Fix #XXX" notation where XXX is the issue number? By including "Fix #XXX" you allow GitHub to close issue #XXX when the PR is merged.

### CODE REVIEW

**Comment by mavaylon1** [comment]
@rly I think I found the solution but need some help to get everything passing. I'm not sure why conda test for py3.7 isn't finding the module. Did I miss something in the run tests workflow? I also need to add the changes to run_all_tests, but I'll do that after run_tests is sorted. I also think these changes should solve #826

**Comment by mavaylon1** [comment]
Fix #822

**Comment by mavaylon1** [comment]
I don't think there needs to be a test for the updates (cov/patch)

**Review by oruebel — CHANGES_REQUESTED** [review]
Should ``docs/ER_Example_Term_Set.ipynb`` file be part of this PR? If not, then please remove it from this PR. 

It looks like there are comments added in ``test_gallery.py`` that may no longer be needed. If so, can you please clean up those comments.

Otherwise this looks good to me.

**Review by oruebel — APPROVED** [review]

**Pull request merged**
