### PR TITLE
Support spec dtypes "bytes" and "short", improve test coverage

### LINKED ISSUE #455: Datetimes are converted to ascii but stored as variable length strings
## Description

Minor bug:
According to 
https://github.com/hdmf-dev/hdmf/blob/dev/src/hdmf/backends/hdf5/h5tools.py#L802 and 
https://nwb-storage.readthedocs.io/en/latest/storage_hdf5.html#dtype-mappings , 

data meeting the `isodatetime` spec are stored as variable length strings in HDF5. However, `ObjectMapper.convert_dtype(...)` converts isodatetime strings to ASCII. The function should convert datetime string to str instead.

## Steps to Reproduce

image

## Environment

    HDMF Version: dev

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/hdmf-dev/hdmf/issues) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?

### PR DESCRIPTION
**Pull request by rly**
## Motivation

Minor changes.

1. Reorder dtypes across files to match https://nwb-storage.readthedocs.io/en/latest/storage_hdf5.html#dtype-mappings to more easily identify missing keys
2. Add missing support for conversion against spec "bytes" and "short", remove unofficial support for "str"
3. Change `function == function` to `function is function`
4. Add missing tests

## Checklist

- [x] Did you update CHANGELOG.md with your changes?
- [x] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?
- [x] Have you ensured the PR clearly describes the problem and the solution?
- [x] Is your contribution compliant with our coding style? This can be checked running `flake8` from the source directory.
- [x] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/hdmf-dev/hdmf/pulls) for the same change?
- [x] Have you included the relevant issue number using "Fix #XXX" notation where XXX is the issue number? By including "Fix #XXX" you allow GitHub to close issue #XXX when the PR is merged.

### CODE REVIEW

**Comment by ajtritt** [comment]
Is there a reason to store ISO date strings as Unicode? They should never contain non-ASCII characters

**Comment by rly** [comment]
Good point... AFAIK there is no reason to store ISO datetimes as Unicode. ASCII should be fine. And variable length ASCII strings is totally normal -- I had thought there was an inconsistency there where ASCII = fixed length string. I will undo the isodatetime - utf8 changes, and update the title and original post to reflect that.

**Comment by ajtritt** [comment]
> I had thought there was an inconsistency there where ASCII = fixed length string.

I'm pretty sure HDF5 allows variable length ASCII strings. And even if not, an ISO date string _could_ always be the same length.

**Comment by rly** [comment]
> I'm pretty sure HDF5 allows variable length ASCII strings. 

Yes, that is how they are currently stored. I was confused and thought ASCII strings could be stored only in fixed length strings in HDF5. I removed the related change from this PR.

**Review by ajtritt — APPROVED** [review]

**Pull request merged**
