### PR TITLE
Fix validator for arrays of special_dtypes

### PR DESCRIPTION
**Pull request by rly**
I think this is a better fix for https://github.com/hdmf-dev/hdmf/issues/68, https://github.com/hdmf-dev/hdmf/pull/69, and https://github.com/NeurodataWithoutBorders/pynwb/issues/966

### CODE REVIEW

**Comment by bendichter** [comment]
this looks good. Would it be possible to create a test for this?

**Comment by t-b** [comment]
@rly Thanks. I'll test that tomorrow.

**Comment by t-b** [comment]
@rly 
The pynwb tests don't pass with this PR here. But they also fail with hdmf master.
Validation in pynwb works again. Thanks!

**Comment by t-b** [comment]
@rly I'll adapt #69 once this PR get's merged.

**Review by ajtritt — APPROVED** [review]

**Pull request merged**
