### PR TITLE
Fix case where non-AbstractContainer is base class

### LINKED ISSUE #443: Fix broken edge case of AbstractContainer multiple inheritance
## Description

`AbstractContainer.__gather_fields()` assumes that, if the class has multiple inheritance, that the highest base class (assuming parents are higher than their children) is an `AbstractContainer`. That might not always be the case and should be checked.  

## Steps to Reproduce

See https://github.com/oruebel/ndx-icephys-meta/issues/76

## Environment

    Python Executable: Conda 
    Python Version: Python 3.7
    Operating System: Windows
    HDMF Version: dev

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/hdmf-dev/hdmf/issues) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?

### PR DESCRIPTION
**Pull request by rly**
## Motivation

Fix #443.

## Checklist

- [ ] Did you update CHANGELOG.md with your changes?
- [x] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?
- [x] Have you ensured the PR clearly describes the problem and the solution?
- [x] Is your contribution compliant with our coding style? This can be checked running `flake8` from the source directory.
- [x] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/hdmf-dev/hdmf/pulls) for the same change?
- [x] Have you included the relevant issue number using "Fix #XXX" notation where XXX is the issue number? By including "Fix #XXX" you allow GitHub to close issue #XXX when the PR is merged.

### CODE REVIEW

**Comment by oruebel** [comment]
I'm wondering whether this is really a bug in HDMF or an error on the user side (i.e., in this case the ndx-icephys extension that I wrote). In Python in general the order in which you inherit from other classes matters, i.e., I'm wondering whether it may be better to throw an error to force developers (in this case me ;-)   ) to fix their classes early on, rather than trying to support "bad code"? 

The fix you added looks good, I'm just wondering whether trying to allow this could cause more trouble down the road, or whether this is a case that we have to support because it is a legitimate use-case?

**Comment by rly** [comment]
In general, I agree, it's hard to think of a use case here. How about if a user wants to create a subclass of both `Container` and maybe `dict` and it is not obvious which class should go earlier/later in the hierarchy?

**Comment by ajtritt** [comment]
I just ran into this problem. Reordering the parent classes did not solve my problem.

**Review by ajtritt — APPROVED** [review]

**Comment by rly** [comment]
@ajtritt Does this branch solve the problem? Reordering the parent classes (assuming the last one is an `AbstractContainer` should have done it; otherwise there might be something else going on)>

**Comment by ajtritt** [comment]
@rly Reordering solved the problem, but then exposed some other problem. I checked out this branch and this solved my problem, so I haven't dug into why reordering didn't work. Based on that, I'd say this fix is the best solution long-term

**Comment by rly** [comment]
Sounds good

**Pull request merged**
