### PR TITLE
Integrate experimental namespace

### PR DESCRIPTION
**Pull request by ajtritt**
## Motivation

Provide way of tagging classes as experimental

## Checklist

- [ ] Did you update CHANGELOG.md with your changes?
- [ ] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?
- [ ] Have you ensured the PR clearly describes the problem and the solution?
- [ ] Is your contribution compliant with our coding style? This can be checked running `flake8` from the source directory.
- [ ] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/hdmf-dev/hdmf/pulls) for the same change?
- [ ] Have you included the relevant issue number using "Fix #XXX" notation where XXX is the issue number? By including "Fix #XXX" you allow GitHub to close issue #XXX when the PR is merged.

### CODE REVIEW

**Comment by ajtritt** [comment]
@rly Is the pynwb-dev-python38 failure expected?

**Comment by rly** [comment]
No, that is odd. The error seems to be with caching the spec:
```
    File "/home/circleci/project/src/hdmf/backends/hdf5/h5tools.py", line 406, in write
      self.__cache_spec()
    File "/home/circleci/project/src/hdmf/backends/hdf5/h5tools.py", line 419, in __cache_spec
      ns_builder = self.__convert_namespace(ns_catalog, ns_name)
    File "/home/circleci/project/src/hdmf/backends/hdf5/h5tools.py", line 298, in __convert_namespace
      builder.add_spec(h5_source, spec)
    File "/home/circleci/project/src/hdmf/utils.py", line 580, in func_call
      return func(args[0], **pargs)
    File "/home/circleci/project/src/hdmf/spec/write.py", line 134, in add_spec
      self.__catalog.auto_register(spec, source)
    File "/home/circleci/project/src/hdmf/utils.py", line 580, in func_call
      return func(args[0], **pargs)
    File "/home/circleci/project/src/hdmf/spec/catalog.py", line 92, in auto_register
      self.register_spec(spec, source_file)
    File "/home/circleci/project/src/hdmf/utils.py", line 580, in func_call
      return func(args[0], **pargs)
    File "/home/circleci/project/src/hdmf/spec/catalog.py", line 45, in register_spec
      raise ValueError("'%s' - cannot overwrite existing specification" % type_name)
  ValueError: 'Data' - cannot overwrite existing specification
```

**Comment by rly** [comment]
I fixed the error. There is a remaining error from a unit test in PyNWB that checked the available namespaces and found a new namespace that was not expected. This is easily fixed. The change should not break backward compatibility.

**Comment by rly** [comment]
This looks good. @ajtritt please update the changelog and review my changes to `src/hdmf/spec/namespace.py`

**Review by rly — DISMISSED** [review]

**Review by rly — DISMISSED** [review]

**Review by rly — APPROVED** [review]

**Pull request merged**
