### PR TITLE
Add multicontainerinterface

### PR DESCRIPTION
**Pull request by bendichter**
Move `MultiContainerInterface` from pynwb.core to hdmf.container. The motivations for this are:
1. allow hdmf and other hdmf derivatives besides pynwb to use these structures
2. allow for automatically generating `MultiContainerInterface` objects from pynwb extensions

### CODE REVIEW

**Comment by rly** [comment]
This PR includes #405. Merge that into dev, then merge dev into this branch to simplify the diff of this PR.

TODO: adds tests of `MultiContainerInterface`. There are currently no tests.

**Comment by rly** [comment]
@bendichter I'll work on adding tests unless you have already started

**Comment by bendichter** [comment]
@rly none besides the src/hdmf/testing/test_MultiContainerInterface.py that were already there

**Comment by rly** [comment]
@bendichter Sounds good. Thanks, I missed those tests (by this project's convention, tests should go in `/tests/unit/` )

**Comment by rly** [comment]
I fixed a bug in `MultiContainerInterface` where if it contains only one item and you call `__getitem__` on it with any key, then it would return the only item, regardless of whether the key matches the item's name.

```python
from pynwb.core import ProcessingModule
from pynwb.core import NWBDataInterface
pm = ProcessingModule('pm_name', 'pm_description')
pm.add(NWBDataInterface('container_name'))
pm['hi']  # returns the NWBDataInterface even though its name doesn't match the key
```

And `MultiContainerInterface` is now an abstract class so you cannot instantiate it, and an error is now raised if you attempt to create an instance of a subclass without defining `__clsconf__` in the subclass.

**Comment by rly** [comment]
I have added a full suite of tests. This PR is now ready for review.

This PR includes changes from #405. Please review that first.

Next steps: after #405 is merged into dev, merge dev into this branch, then merge this into dev.

**Review by ajtritt — DISMISSED** [review]

**Comment by rly** [comment]
This is now ready to review and merge

**Review by oruebel — APPROVED** [review]

**Pull request merged**
