### PR TITLE
Codespell: fixing typos, added workflow, config

### PR DESCRIPTION
**Pull request by yarikoptic**
## Motivation

Make world a better place

## How to test the behavior?

run `codespell` on your code ;)

## Checklist

- [x] Did you update CHANGELOG.md with your changes?
- [x] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?
- [x] Have you ensured the PR clearly describes the problem and the solution?
- [x] Is your contribution compliant with our coding style? This can be checked running `flake8` from the source directory.
- [x] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/hdmf-dev/hdmf/pulls) for the same change?

### CODE REVIEW

**Comment by bendichter** [comment]
This looks great! Thanks @yarikoptic ! @CodyCBakerPhD  this looks like something you'd like ;-)

**Comment by CodyCBakerPhD** [comment]
@bendichter Already ahead on this: https://github.com/catalystneuro/neuroconv/pull/325

But likely won't have time to actually fix the misspellings for a few days

**Comment by rly** [comment]
@yarikoptic thanks for the PR. Can you revert your changes to the submodule? And add a note to the changelog. Thanks.

**Comment by yarikoptic** [comment]
done!  I really hope you folks automate CHANGELOG generation at some point.  I am getting spoiled by `auto` and our custom `datalad/release-action` ;)

**Review by rly — APPROVED** [review]

**Pull request merged**
