### PR TITLE
fix MPI support

### LINKED ISSUE #362: parallel io
## Feature Request

The basic necessity is to add arguments to `NWBHDF5IO` and similar utilities to facilitate opening an NWB file with MPI and ensure that data can be read/written in parallel.

In addition, we would like to implement parallel reading/writing tools for NWB. We have developed similar tools in [neuroh5](https://bitbucket.org/ivan_raikov/neuroh5/src).

### PR DESCRIPTION
**Pull request by bendichter**
## Motivation

This mirrors a change we made to pynwb to fix interfacing with MPI.
fix https://github.com/NeurodataWithoutBorders/pynwb/issues/362


## How to test the behavior?
```python
from mpi4py import MPI                                                                                                
import h5py                                                                                                           
                                                                                                                      
from dateutil import tz                                                                                               
                                                                                                                      
from pynwb.form.backends.hdf5.h5tools import HDF5IO                                                                   
from pynwb import NWBHDF5IO, NWBFile, TimeSeries                                                                      
from datetime import datetime                                                                                         
                                                                                                                      
start_time = datetime(2018, 4, 25, 2, 30, 3, tzinfo=tz.gettz('US/Pacific'))                                           
                                                                                                                      
fname = 'test_parallel_pynwb.nwb'                                                                                     
                                                                                                                      
rank = MPI.COMM_WORLD.rank  # The process ID (integer 0-3 for 4-process run)                                          
                                                                                                                      
if not rank:                                                                                                          
    nwbfile = NWBFile('aa', 'aa', datetime.now())                                                                     
    nwbfile.add_acquisition(TimeSeries('ts_name', description='desc', data=[0, 0, 0, 0], rate=100., unit='m'))        
    with NWBHDF5IO(fname, 'w') as io:                                                                                 
        io.write(nwbfile)                                                                                             
                                                                                                                      
MPI.COMM_WORLD.Barrier()                                                                                              
                                                                                                                      
with NWBHDF5IO(fname, 'a', comm=MPI.COMM_WORLD) as io:                                                                
        nwbfile = io.read()
        print(rank)                                                                                           
        nwbfile.acquisition['ts_name'].data[rank] = rank
```

## Checklist

- [ ] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?
- [ ] Have you ensured the PR description clearly describes problem and the solution?
- [ ] Is your contribution compliant with our coding style ? This can be checked running `flake8` from the source directory.
- [ ] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/hdmf-dev/hdmf/pulls) for the same change?
- [ ] Have you included the relevant issue number using `#XXX` notation where `XXX` is the issue number ? By including "Fix #XXX" you allow GitHub to close the corresponding issue.

### CODE REVIEW

**Comment by bendichter** [comment]
since we have moved the backend to the hdmf repo, I am closing this PR in favor of

https://github.com/hdmf-dev/hdmf/pull/14

**Comment by ajtritt** [comment]
Can you resubmit this so Circle runs?

**Comment by bendichter** [comment]
@ajtritt can you merge this? I still don't have permission

**Comment by bendichter** [comment]
@ajtritt can we merge this?

**Review by ajtritt — APPROVED** [review]

**Pull request merged**
