### PR TITLE
add unique identifier to Container objects

### LINKED ISSUE #92: Add unique identifiers to data_types
data_type should be uniquely identifiable. This will help with identifying and retrieving of objects from a HDMF dataset. The proposed solution is as follows:

1. Any object with a data_type and namespace attribute will also have a new attribute, called `object_id`
2. `object_id` will be a UUID-4 hexstring

## Checklist

- [X] Have you ensured the feature or change was not already [reported](https://github.com/hdmf-dev/hdmf/issues) ?
- [X] Have you included a brief and descriptive title?
- [X] Have you included a clear description of the problem you are trying to solve?
- [X] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [X] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?

### PR DESCRIPTION
**Pull request by ajtritt**
## Motivation

Add identifier so Container objects can be uniquely identified from a File.

Fix #92 

## How to test the behavior?
```python
nwb = NWBFile(...)
ts = TimeSeries(...)
nwb.add_acquisition(ts)
with NWBHDF5IO('test.nwb', 'w') as f:
    f.write(nwb)
ts is nwb.objects[ts.object_id]
```

## Checklist

- [X] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured the PR description clearly describes problem and the solution?
- [X] Is your contribution compliant with our coding style ? This can be checked running `flake8` from the source directory.
- [X] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/hdmf-dev/hdmf/pulls) for the same change?
- [X] Have you included the relevant issue number using `#XXX` notation where `XXX` is the issue number ? By including "Fix #XXX" you allow GitHub to close the corresponding issue.

### CODE REVIEW

**Review by rly — DISMISSED** [review]

**Review by rly — DISMISSED** [review]

**Review by rly — DISMISSED** [review]

**Comment by bendichter** [comment]
Will this break read on previously written datasets?

**Comment by rly** [comment]
@bendichter No, we tested this on a file without object_ids. `object_id` would be set to None.

**Comment by bendichter** [comment]
Ok sounds good then

**Review by rly — DISMISSED** [review]

**Comment by rly** [comment]
@oruebel I think this is good to go, but I wrote part of it, so I think someone else should review it.

**Comment by rly** [comment]
@ajtritt I added a commented out docval string for `Container.__new__` for documentation. docval does not work there, probably because of the `args`, but I'm not sure.

**Comment by rly** [comment]
@oruebel could you please review this? it is holding up https://github.com/NeurodataWithoutBorders/pynwb/pull/994 and both are necessary for NWB-DataJoint integration

**Review by oruebel — APPROVED** [review]

**Pull request merged**
