### PR TITLE
make untyped dataset of references expandable

### LINKED ISSUE #1181: [Bug]: untyped dataset of references cannot be set as expandable
### What happened?

With appending to an electrodes table, the group column cannot be set as expandable. 

I have a working solution to this and just need to add the tests.

### Steps to Reproduce

```python
from datetime import datetime
from uuid import uuid4
from dateutil import tz

from pynwb import NWBHDF5IO, NWBFile, H5DataIO

session_start_time = datetime(2018, 4, 25, 2, 30, 3, tzinfo=tz.gettz("US/Pacific"))

# setup NWBFile
nwbfile = NWBFile(
    session_description="Mouse exploring an open field",  # required
    identifier=str(uuid4()),  # required
    session_start_time=session_start_time,  # required
)

# add column
device = nwbfile.create_device(name="array", description="an array", manufacturer="company")

# create an electrode group
electrode_group = nwbfile.create_electrode_group(
    name="shank0",
    description="electrode group for shank 0",
    device=device,
    location="brain area",
)

# add electrode to the electrode table
nwbfile.add_electrode(group=electrode_group, location="brain area",)
nwbfile.electrodes.id.set_data_io(H5DataIO, {'maxshape': (None,), 'chunks': True})
nwbfile.electrodes.group.set_data_io(H5DataIO, {'maxshape': (None,), 'chunks': True})
nwbfile.electrodes.group_name.set_data_io(H5DataIO, {'maxshape': (None,), 'chunks': True})
nwbfile.electrodes.location.set_data_io(H5DataIO, {'maxshape': (None,), 'chunks': True})

with NWBHDF5IO("test_append_electrodes_table.nwb", "w") as io:
    io.write(nwbfile)

with NWBHDF5IO("test_append_electrodes_table.nwb", mode="a") as io:
    nwbfile = io.read()
    electrode_group = nwbfile.electrode_groups["shank0"]
    
    nchannels = 4
    for ielec in range(nchannels):
        nwbfile.add_electrode(
            group=electrode_group,
            location="brain area",
        )

    io.write(nwbfile)

with NWBHDF5IO("test_append_electrodes_table.nwb", "r") as io:
    nwbfile = io.read()
    print(nwbfile.electrodes.to_dataframe())
```

### Traceback

```pytb
Traceback (most recent call last):
  File "/Users/smprince/anaconda3/envs/pynwb/lib/python3.11/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smprince/anaconda3/envs/pynwb/lib/python3.11/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/Users/smprince/.vscode/extensions/ms-python.debugpy-2024.10.0-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/Users/smprince/.vscode/extensions/ms-python.debugpy-2024.10.0-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/Users/smprince/.vscode/extensions/ms-python.debugpy-2024.10.0-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/Users/smprince/.vscode/extensions/ms-python.debugpy-2024.10.0-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smprince/.vscode/extensions/ms-python.debugpy-2024.10.0-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/smprince/.vscode/extensions/ms-python.debugpy-2024.10.0-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/Users/smprince/Documents/code/pynwb/issue_scripts/electrode_table_testing.py", line 43, in <module>
    nwbfile.add_electrode(
  File "/Users/smprince/Documents/code/hdmf/src/hdmf/utils.py", line 668, in func_call
    return func(args[0], **pargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smprince/Documents/code/pynwb/src/pynwb/file.py", line 725, in add_electrode
    self.electrodes.add_row(**d)
  File "/Users/smprince/Documents/code/hdmf/src/hdmf/utils.py", line 668, in func_call
    return func(args[0], **pargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smprince/Documents/code/hdmf/src/hdmf/common/table.py", line 715, in add_row
    c.add_row(data[colname])
  File "/Users/smprince/Documents/code/hdmf/src/hdmf/utils.py", line 668, in func_call
    return func(args[0], **pargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smprince/Documents/code/hdmf/src/hdmf/common/table.py", line 52, in add_row
    self.append(val)
  File "/Users/smprince/Documents/code/hdmf/src/hdmf/container.py", line 948, in append
    self.__data = append_data(self.__data, arg)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smprince/Documents/code/hdmf/src/hdmf/data_utils.py", line 23, in append_data
    data.append(arg)
  File "/Users/smprince/Documents/code/hdmf/src/hdmf/backends/hdf5/h5_utils.py", line 123, in append
    append_data(self.dataset, ref)
  File "/Users/smprince/Documents/code/hdmf/src/hdmf/data_utils.py", line 36, in append_data
    data.resize(shape)
  File "/Users/smprince/anaconda3/envs/pynwb/lib/python3.11/site-packages/h5py/_hl/dataset.py", line 666, in resize
    raise TypeError("Only chunked datasets can be resized")
TypeError: Only chunked datasets can be resized
```

### Operating System

macOS

### Python Executable

Conda

### Python Version

3.11

### Package Versions

_No response_

### PR DESCRIPTION
**Pull request by stephprince**
## Motivation

Fix https://github.com/hdmf-dev/hdmf/issues/1181

To do: 
- [x] add tests

## How to test the behavior?
```python
from datetime import datetime
from uuid import uuid4
from dateutil import tz

from pynwb import NWBHDF5IO, NWBFile, H5DataIO

session_start_time = datetime(2018, 4, 25, 2, 30, 3, tzinfo=tz.gettz("US/Pacific"))

# setup NWBFile
nwbfile = NWBFile(
    session_description="Mouse exploring an open field",  # required
    identifier=str(uuid4()),  # required
    session_start_time=session_start_time,  # required
)

# add column
device = nwbfile.create_device(name="array", description="an array", manufacturer="company")

# create an electrode group
electrode_group = nwbfile.create_electrode_group(
    name="shank0",
    description="electrode group for shank 0",
    device=device,
    location="brain area",
)

# add electrode to the electrode table
nwbfile.add_electrode(group=electrode_group, location="brain area",)
nwbfile.electrodes.id.set_data_io(H5DataIO, {'maxshape': (None,), 'chunks': True})
nwbfile.electrodes.group.set_data_io(H5DataIO, {'maxshape': (None,), 'chunks': True})
nwbfile.electrodes.group_name.set_data_io(H5DataIO, {'maxshape': (None,), 'chunks': True})
nwbfile.electrodes.location.set_data_io(H5DataIO, {'maxshape': (None,), 'chunks': True})

with NWBHDF5IO("test_append_electrodes_table.nwb", "w") as io:
    io.write(nwbfile)

with NWBHDF5IO("test_append_electrodes_table.nwb", mode="a") as io:
    nwbfile = io.read()
    electrode_group = nwbfile.electrode_groups["shank0"]
    
    nchannels = 4
    for ielec in range(nchannels):
        nwbfile.add_electrode(
            group=electrode_group,
            location="brain area",
        )

    io.write(nwbfile)

with NWBHDF5IO("test_append_electrodes_table.nwb", "r") as io:
    nwbfile = io.read()
    print(nwbfile.electrodes.to_dataframe())
```

## Checklist

- [x] Did you update `CHANGELOG.md` with your changes?
- [x] Does the PR clearly describe the problem and the solution?
- [x] Have you reviewed our [Contributing Guide](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst)?
- [x] Does the PR use "Fix #XXX" notation to tell GitHub to close the relevant issue numbered XXX when the PR is merged?

### CODE REVIEW

**Comment by stephprince** [comment]
@mavaylon1 These are the changes related to our issue triaging that we will discuss testing set up for next week.

**Review by mavaylon1 — APPROVED** [review]

**Comment by cboulay** [comment]
Here is an expanded test that uses 2 electrode groups and 2 electrical series linked to different electrode ranges. I was surprised by the need to call `io.write(nwbfile)` before adding electrodes to the second group, as this wasn't required of the first group.

```Python
from datetime import datetime
from uuid import uuid4
from dateutil import tz

import numpy as np
from pynwb import NWBHDF5IO, NWBFile, H5DataIO, ecephys

session_start_time = datetime(2018, 4, 25, 2, 30, 3, tzinfo=tz.gettz("US/Pacific"))

# setup NWBFile
nwbfile = NWBFile(
    session_description="Mouse exploring an open field",  # required
    identifier=str(uuid4()),  # required
    session_start_time=session_start_time,  # required
)

# add column
nwbfile.add_electrode_column(name="label", description="electrode label")

# add device
device = nwbfile.create_device(name="array", description="an array", manufacturer="company")

# create an electrode group
electrode_group = nwbfile.create_electrode_group(
    name="shank0",
    description="electrode group for shank 0",
    device=device,
    location="brain area",
)

# add electrode to the electrode table
n0 = 2
for ch_ix in range(n0):
    nwbfile.add_electrode(
        group=electrode_group,
        location="brain area",
        label=f"ch{ch_ix}",
    )

# Make the fields expandable
nwbfile.electrodes.id.set_data_io(H5DataIO, {'maxshape': (None,), 'chunks': True})
nwbfile.electrodes.group.set_data_io(H5DataIO, {'maxshape': (None,), 'chunks': True})
nwbfile.electrodes.group_name.set_data_io(H5DataIO, {'maxshape': (None,), 'chunks': True})
nwbfile.electrodes.location.set_data_io(H5DataIO, {'maxshape': (None,), 'chunks': True})
nwbfile.electrodes.label.set_data_io(H5DataIO, {'maxshape': (None,), 'chunks': True})

el_tbl_region = nwbfile.create_electrode_table_region(region=list(range(n0)), description=f"elec region 0")
series = ecephys.ElectricalSeries(
    name="series0",
    description="series0 descr",
    data=np.random.randn(50, n0),
    electrodes=el_tbl_region,
    starting_time=0.0,
    rate=2000.0,
)
nwbfile.add_acquisition(series)

with NWBHDF5IO("test_append_electrodes_table.nwb", "w") as io:
    io.write(nwbfile)

with NWBHDF5IO("test_append_electrodes_table.nwb", mode="a") as io:
    nwbfile = io.read()

    electrode_group = nwbfile.create_electrode_group(
        name="shank1",
        description="electrode group for shank 1",
        device=nwbfile.devices["array"],
        location="brain area",
    )
    io.write(nwbfile)  # Surprised this is necessary to avoid error.

    n1 = 4
    for ielec in range(n0, n0 + n1):
        nwbfile.add_electrode(
            group=electrode_group,
            location="brain area",
            label=f"ch{ielec}",
        )
    el_tbl_region = nwbfile.create_electrode_table_region(
        region=list(range(n0, n0 + n1)),
        description=f"elec region 1"
    )
    series = ecephys.ElectricalSeries(
        name="series1",
        description="series1 descr",
        data=np.random.randn(50, n1),
        electrodes=el_tbl_region,
        starting_time=0.1,
        rate=1000.0,
    )
    nwbfile.add_acquisition(series)

    io.write(nwbfile)

with NWBHDF5IO("test_append_electrodes_table.nwb", "r") as io:
    nwbfile = io.read()
    el_df = nwbfile.electrodes.to_dataframe()
    assert el_df.label.tolist() == [f"ch{ielec}" for ielec in range(n0 + n1)]

    eldf0 = nwbfile.acquisition["series0"].electrodes.to_dataframe()
    assert eldf0.label.tolist() == [f"ch{ielec}" for ielec in range(n0)]
    
    eldf1 = nwbfile.acquisition["series1"].electrodes.to_dataframe()
    assert eldf1.label.tolist() == [f"ch{ielec}" for ielec in range(n0, n0 + n1)]

```

**Comment by stephprince** [comment]
Thanks for sharing @cboulay! I think this would be a great example for our pynwb documentation: https://github.com/NeurodataWithoutBorders/pynwb/issues/1951.

If I remember correctly, io.write() needs to be called again because of issues creating an HDF5 reference to the electrode group object that isn't in the file yet, but @mavaylon1 could you elaborate on this and explain why it is needed when appending in particular?

**Comment by cboulay** [comment]
By the way, thank you for adding this feature! It enabled us to get past one of the sticking points we had when streaming to pynwb.
Despite the pasted code working well, in my weird asynch ezmsg class I actually still have the error when adding new electrodes to a secondary electrode group despite calling that extra io.write so for now I'm limited to a single unified "group" per session. That's fine for us for now, but I would be interested in understanding how this works a little better to maybe identify my specific problem.

**Pull request merged**
