### PR TITLE
Add HDF5IO.get_namespaces() method

### PR DESCRIPTION
**Pull request by rly**
## Motivation

Work for https://github.com/NeurodataWithoutBorders/nwb-schema/issues/319#issuecomment-781469270

Add `HDF5IO.get_namespaces(path=path, file=file)` method which returns a dict of namespace name mapped to the
namespace version (the largest one if there are multiple) for each namespace cached in the given HDF5 file (`path` and/or `file` must be provided)

I also did some refactoring.

@yarikoptic let me know what you think of this. Once released, since `NWBHDF5IO` extends `HDF5IO`, you can also call `NWBHDF5IO.get_namespaces(path=path, file=file)`.

We could also make `get_namespaces` read the cached spec data into `SpecNamespace` objects  which contains all the properties of a namespace (e.g., docstring, authors, dependencies). The downside is that this would make `SpecNamespace` more public/user-facing than I think we would like. The contents could be converted into a dictionary though.

We could also make `get_namespaces` show *all* of the versions cached for each namespace in a file. I think this would be confusing and not so useful though since the versions not reported are not used by HDMF. Really, they should be removed when a later version is written, but there might be value in preserving that history.

## How to test the behavior?
```python
filepath = 'test.nwb'
print(HDF5IO.get_namespaces(path=filepath))

file = h5py.File('test.nwb', 'r')
print(HDF5IO.get_namespaces(file=file))
```

## Checklist

- [x] Did you update CHANGELOG.md with your changes?
- [x] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?
- [x] Have you ensured the PR clearly describes the problem and the solution?
- [x] Is your contribution compliant with our coding style? This can be checked running `flake8` from the source directory.
- [x] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/hdmf-dev/hdmf/pulls) for the same change?
- [x] Have you included the relevant issue number using "Fix #XXX" notation where XXX is the issue number? By including "Fix #XXX" you allow GitHub to close issue #XXX when the PR is merged.

### CODE REVIEW

**Comment by oruebel** [comment]
> We could also make `get_namespaces` read the cached spec data into `SpecNamespace` .... The contents could be converted into a dictionary though.

I think either way should be fine. I think providing the complete details would probably be more useful.

> We could also make `get_namespaces` show _all_ of the versions cached for each namespace in a file

I think it would make sense to just make this a configurable option, e.g., `most_recent_only=true` so that by default we only return the most recent versions but if the user really wants to they can get all versions. At least in this way, the behavior is explicit and by default the function still behaves as expected.

**Comment by yarikoptic** [comment]
Doiing a sweep over dandiarchive files... to report in full more later, meanwhile - spotting
```shell
$> ../tools/hdmf-get-namespaces.py /mnt/backup/dandi/dandisets/000004/sub-P10HMH/sub-P10HMH_ses-20060901_ecephys+image.nwb 
Extracting spaces... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--
Traceback (most recent call last):
  File "../tools/hdmf-get-namespaces.py", line 27, in <module>
    namespaces = HDF5IO.get_namespaces(path=filepath)
  File "/home/yoh/proj/dandi/hdmf/src/hdmf/utils.py", line 580, in func_call
    return func(args[0], **pargs)
  File "/home/yoh/proj/dandi/hdmf/src/hdmf/backends/hdf5/h5tools.py", line 207, in get_namespaces
    return cls.__get_namespaces(open_file_obj)
  File "/home/yoh/proj/dandi/hdmf/src/hdmf/backends/hdf5/h5tools.py", line 217, in __get_namespaces
    spec_group = file_obj[file_obj.attrs[SPEC_LOC_ATTR]]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/yoh/miniconda3/lib/python3.8/site-packages/h5py/_hl/attrs.py", line 60, in __getitem__
    attr = h5a.open(self._id, self._e(name))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5a.pyx", line 77, in h5py.h5a.open
KeyError: "Can't open attribute (can't locate attribute: '.specloc')"
```

h5py 2.10.0, hdmf 2.4.0-7-g3eb1bd7 ...

**Comment by yarikoptic** [comment]
FWIW -- here is the summary from 

<details>
<summary>this ad-hoc script</summary> 

```python
#!/usr/bin/env python3

# Needs HDMF from https://github.com/hdmf-dev/hdmf/pull/527
import sys

from collections import Counter, defaultdict

from hdmf.backends.hdf5 import HDF5IO
from rich import print
from rich.progress import track
from rich import pretty
pretty.install()


all_versions = defaultdict(Counter)
exceptions = Counter()

if len(sys.argv) > 1:
   filepaths = sys.argv[1:]
else:
   filepaths = list(sys.stdin)

for filepath in track(filepaths, description="Extracting spaces..."):
    filepath = filepath.rstrip()  # for stdin ones
    #print(filepath) # , soft_wrap=True)
    try:
       namespaces = HDF5IO.get_namespaces(path=filepath)
    except Exception as exc:
    #except IOError as exc:
       print(f"Exception on {filepath}: {exc}")
       exceptions[str(exc)] += 1
       continue
    for e, v in namespaces.items():
        all_versions[e][v] += 1
    # print(filepath, namespaces)

print(f"\nSummary:")
print(f"  Files: {len(filepaths)}")
print(f"  Counts: ")
for ext, versions in sorted(all_versions.items()):
    versions = dict(versions)
    print(f"    {ext}: {versions}")
if exceptions:
   print("  Exceptions: %d   %s", sum(exceptions.values()), exceptions)

```
</details>

```
Summary:
  Files: 15897
  Counts: 
    AIBS_ecephys: {'unversioned': 39}
    core: {'2.2.5': 12401, '2.2.2': 772, '2.0.2': 58, '2.1.0': 2185, '2.0.1': 297, '2.2.4': 64}
    hdmf-common: {'1.3.0': 612, '1.1.3': 7231, '1.0.0': 481, '1.2.0': 6907}
    ndx-aibs-ecephys: {'0.2.0': 383}
    ndx-dandi-icephys: {'0.3.0': 1513, '0.2.0': 297}
    ndx-events: {'0.2.0': 20}
    ndx-grayscalevolume: {'0.0.2': 1}
    ndx-ibl-metadata: {'0.1.0': 6615}
    ndx-icephys-meta: {'0.1.0': 1}
    ndx-mies: {'0.1.0': 4817}
    ndx-spectrum: {'0.1.0': 1, '0.2.2': 6616}
  Exceptions: %d   %s 120
Counter({'"Can\'t open attribute (can\'t locate attribute: \'.specloc\')"': 120})
```

dandisets on which that exception happens: 4, 19, 27, 29

**Comment by yarikoptic** [comment]
is this `KeyError` issue could be easily addressed or a bit more profound?

**Comment by rly** [comment]
@yarikoptic I just fixed this issue and tested it on the DANDI data using your ad hoc script (thanks!) and got no exceptions. 

The .specloc error occurred on some older files written with MatNWB that do not have any cached namespaces.

**Comment by rly** [comment]
For some reason, the numbers on my output are a little different than yours. Not sure why.
```
Summary:
  Files: 15879
  Counts:
    AIBS_ecephys: {'unversioned': 39}
    core: {'2.2.5': 12382, '2.2.2': 772, '2.0.2': 58, '2.1.0': 2186, '2.0.1': 297, '2.2.4': 64}
    hdmf-common: {'1.3.0': 593, '1.1.3': 7232, '1.0.0': 481, '1.2.0': 6907}
    ndx-aibs-ecephys: {'0.2.0': 383}
    ndx-dandi-icephys: {'0.3.0': 1513, '0.2.0': 297}
    ndx-events: {'0.2.0': 20}
    ndx-grayscalevolume: {'0.0.2': 1}
    ndx-ibl-metadata: {'0.1.0': 6615}
    ndx-icephys-meta: {'0.1.0': 2}
    ndx-mies: {'0.1.0': 4817}
    ndx-spectrum: {'0.1.0': 1, '0.2.2': 6616}
```

**Comment by yarikoptic** [comment]
> The .specloc error occurred on some older files written with MatNWB that do not have any cached namespaces.

Shouldn't the function just handle such cases gracefully? Eg None could be a sensible return

**Comment by yarikoptic** [comment]
This is a live collection, so might be there were changes since then?

**Comment by rly** [comment]
Ah, that makes sense.

**Review by oruebel — APPROVED** [review]
Looks good. 

On a separate note, is there ever a situation where we want both ``path`` and ``file`` specified as parameter? If not, then it may be simpler to just have one parameter that permits either a path or file.

**Comment by rly** [comment]
> On a separate note, is there ever a situation where we want both path and file specified as parameter? If not, then it may be simpler to just have one parameter that permits either a path or file.

No. This was done to maintain consistency with `HDF5IO.__init__(...)` and `HDF5IO.load_namespaces(...)`. Happy to change that in a separate PR, but if so, we should probably change that for all three.

**Comment by oruebel** [comment]
> No. This was done to maintain consistency with `HDF5IO.__init__(...)` and `HDF5IO.load_namespaces(...)`. Happy to change that in a separate PR, but if so, we should probably change that for all three.

Makes sense. I agree that for this PR it makes sense to keep it as is and make the get_namespaces consistent with the other functions. It may also not be worth the hassle of breaking compatibility at this point. This was mainly just a curious question. This PR is good to go from my end.

**Pull request merged**
